In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/Users/guanxi/Desktop/Final Project/label and feature dataset.csv')

In [3]:
data.columns.tolist()

['FIPS',
 'Qualifying Name',
 'State Postal Abbreviation',
 'Summary Level',
 'Geographic Component',
 'State (FIPS Code)',
 'County of current residence',
 'Census Tract',
 'Area Name',
 'Tribal Tract',
 'Total Population',
 'Total Population:',
 'Total Population: White Alone',
 'Total Population: Black or African American Alone',
 'Total Population: Asian Alone',
 '% Total Population: White Alone',
 '% Total Population: Black or African American Alone',
 '% Total Population: Asian Alone',
 'Per Capita Income (In 2022 Inflation Adjusted Dollars)',
 'Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved WithIn Same County',
 'Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different County WithIn Same State',
 'Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different State',
 'Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Abroad',
 '% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved WithIn Same County',
 '% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different County WithIn Same State',
 '% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different State',
 '% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Abroad',
 'Average Commute to Work (In Min)',
 'Workers 16 Years and Over:',
 'Workers 16 Years and Over: Car, Truck, or Van',
 'Workers 16 Years and Over: Public Transportation (Includes Taxicab)',
 'Workers 16 Years and Over: Bicycle',
 'Workers 16 Years and Over: Walked',
 '% Workers 16 Years and Over: Car, Truck, or Van',
 '% Workers 16 Years and Over: Public Transportation (Includes Taxicab)',
 '% Workers 16 Years and Over: Bicycle',
 '% Workers 16 Years and Over: Walked',
 'Gini Index']

In [ ]:
data["Average Commute to Work (In Min)"]
data["% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Abroad"]
data["% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different County WithIn Same State"]
data["% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different State"]
data["% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved WithIn Same County"]
data["% Workers 16 Years and Over: Bicycle"]
data["% Workers 16 Years and Over: Car, Truck, or Van"]
data["% Workers 16 Years and Over: Public Transportation (Includes Taxicab)"]
data["% Workers 16 Years and Over: Walked"]
data["FIPS"]

In [4]:
selected_columns =["Average Commute to Work (In Min)",
                   "% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Abroad",
                   "% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different County WithIn Same State",
                   "% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different State",
                   "% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved WithIn Same County",
                   "% Workers 16 Years and Over: Bicycle",
                   "% Workers 16 Years and Over: Car, Truck, or Van",
                   "% Workers 16 Years and Over: Public Transportation (Includes Taxicab)",
                   "% Workers 16 Years and Over: Walked",
                   "FIPS"]

In [5]:
spatial = data.loc[:,selected_columns].copy()

In [6]:
spatial

,Average Commute to Work (In Min),% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Abroad,% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different County WithIn Same State,% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different State,% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved WithIn Same County,% Workers 16 Years and Over: Bicycle,"% Workers 16 Years and Over: Car, Truck, or Van",% Workers 16 Years and Over: Public Transportation (Includes Taxicab),% Workers 16 Years and Over: Walked,FIPS
0,32.0,0.00,0.65,1.29,1.02,0.00,48.74,9.17,5.82,6001400100
1,34.0,0.00,2.45,4.10,1.65,3.29,27.76,25.53,1.87,6001400200
2,36.0,1.64,2.93,3.64,7.65,3.21,31.29,27.90,2.94,6001400300
3,32.0,0.22,1.22,0.44,3.72,6.31,37.56,21.38,4.48,6001400400
4,29.0,0.00,3.28,2.37,7.05,5.61,43.76,18.51,1.67,6001400500
...,...,...,...,...,...,...,...,...,...,...
9124,12.0,5.34,8.74,22.14,5.94,0.00,83.33,3.37,7.74,6115040902
9125,31.0,0.00,0.00,0.00,1.07,0.00,79.63,0.00,0.00,6115041001
9126,41.0,0.00,0.00,0.00,3.07,0.00,89.80,0.00,0.95,6115041002
9127,36.0,0.00,0.75,0.26,0.62,0.00,80.65,0.19,0.00,6115041101
9128,40.0,0.00,6.15,0.00,5.52,0.00,83.21,1.27,4.33,6115041102

In [7]:
poi = pd.read_excel('/Users/guanxi/Desktop/Final Project/poi.xlsx')

In [8]:
poi

           GEOID  sustenance  entertainment  health  financial  edu
0     6001400100           4              3       2          2    2
1     6001400200          18              2       2          4    2
2     6001400300          38              3       4          2    2
3     6001400400          13              3       3          2    2
4     6001400500          14              2       2          2    2
...          ...         ...            ...     ...        ...  ...
9124  6115040902           2              2       2          2    3
9125  6115041001           2              2       2          2    4
9126  6115041002           2              2       2          2    4
9127  6115041101           2              2       2          2    3
9128  6115041102           2              2       2          2    3

[9129 rows x 6 columns]

In [10]:
feature = pd.merge(poi,spatial,how="inner",left_on="GEOID",right_on="FIPS")

In [13]:
feature

,sustenance,entertainment,health,financial,edu,Average Commute to Work (In Min),% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Abroad,% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different County WithIn Same State,% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different State,% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved WithIn Same County,% Workers 16 Years and Over: Bicycle,"% Workers 16 Years and Over: Car, Truck, or Van",% Workers 16 Years and Over: Public Transportation (Includes Taxicab),% Workers 16 Years and Over: Walked,FIPS
0,4,3,2,2,2,32.0,0.00,0.65,1.29,1.02,0.00,48.74,9.17,5.82,6001400100
1,18,2,2,4,2,34.0,0.00,2.45,4.10,1.65,3.29,27.76,25.53,1.87,6001400200
2,38,3,4,2,2,36.0,1.64,2.93,3.64,7.65,3.21,31.29,27.90,2.94,6001400300
3,13,3,3,2,2,32.0,0.22,1.22,0.44,3.72,6.31,37.56,21.38,4.48,6001400400
4,14,2,2,2,2,29.0,0.00,3.28,2.37,7.05,5.61,43.76,18.51,1.67,6001400500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9124,2,2,2,2,3,12.0,5.34,8.74,22.14,5.94,0.00,83.33,3.37,7.74,6115040902
9125,2,2,2,2,4,31.0,0.00,0.00,0.00,1.07,0.00,79.63,0.00,0.00,6115041001
9126,2,2,2,2,4,41.0,0.00,0.00,0.00,3.07,0.00,89.80,0.00,0.95,6115041002
9127,2,2,2,2,3,36.0,0.00,0.75,0.26,0.62,0.00,80.65,0.19,0.00,6115041101
9128,2,2,2,2,3,40.0,0.00,6.15,0.00,5.52,0.00,83.21,1.27,4.33,6115041102

In [12]:
feature = feature.drop(columns=["GEOID"])

In [14]:
feature.to_excel("/Users/guanxi/Desktop/Final Project/feature.xlsx")